baseURL = "https://hlcooll.github.io/"
languageCode = "en-us"
title = "hlcooll"


theme = "hyde"

[Menus]
  main = [
      {Name = "Github", URL = "https://github.com/hlcooll"},
      
  ]

[params]
  description = "blog"
  themeColor = "theme-base-0d"
  layoutReverse = true
  disqusShortname = "spf13"
  googleAnalytics = "UA-180227187-1"

